version : '3'

services :
  nginx:
    build: nginx
    container_name: nginx
    ports:
      - 82:80
      - 444:443
    #restart: always
    
  wordpress:
    build: wordpress
    container_name: wordpress
    ports:
      - 81:80
      - 442:443
    #restart: always    
